### ISSUE TITLE
Inability to Drag Columns on Tablets, Mobiles, or Touch Devices

### ISSUE THREAD

**Issue by Shankar3474** [KevinVandy/material-react-table#1117] opened 2024-04-23 14:21 UTC
### material-react-table version

v2.11.1

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

While column dragging functions as expected on laptops or PCs using a mouse cursor, it is not achievable on mobile or tablet devices due to the absence of a cursor. Touch interactions do not enable column movement or dragging.
I've attached the video for your ready reference.

Thanks in advance.

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/153281510/5a90060c-7c82-42bc-bec6-5fc25b6a8cb7

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2024-05-08 04:46
duplicate of #577

**Closed as completed by KevinVandy** 2024-05-08 04:46 UTC
