### ISSUE TITLE
Rows disappear exiting full screen

### ISSUE THREAD

**Issue by duckboy81** [KevinVandy/material-react-table#311] opened 2023-01-11 01:03 UTC
### material-react-table version

v1.5.6

### react & react-dom versions

v5.11.4 & v18.0.10

### Describe the bug and the steps to reproduce it

Troubleshooting this right now. It appears the bad combo is `enableRowVirtualization` and `enableBottomToolbar`. Disabling either one of these will prevent the issue.

Digging into it, `MRT_BottomToolbar` seems to be the culprit. If you pass your own `renderBottomToolbar`, `MRT_BottomToolbar` is not used and there is no issue. 

Removing the following `ref` prop from the `Toolbar` component in `MRT_BottomToolbar` seems to prevent the issue, but I'm doing some more research now.

https://github.com/KevinVandy/material-react-table/blob/aa72893599d091fd0a77f7d1732219f36e13e33d/packages/material-react-table/src/toolbar/MRT_BottomToolbar.tsx#L45-L51

Interestingly, manually attaching my own `MutationObserver` to the "table body section" (I've since forgot what it's actually called) would show that the "table body section" is removed from DOM and the observer loses any new updates when the bug is occurring. When things work normally, the `MutationObserver` is unaffected and new updates are passed correctly.

The final update the `MutationObserver` sees when exiting fullscreen is a `0px` "table body section" height so all rows are removed except for the number of rows specified in the `overscan` setting.

#259
      

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/gracious-jepsen-ndef3b?file=/src/TS.tsx

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2023-01-11 01:22
Nice investigation, was going to say that it sounds like a duplicate of #259 , but yeah, this still seems to be an issue. The toolbar ref being a culprit would be really weird, but possible I guess. I thought it was an issue with `@tanstack/react-virutal` itself, but probably has to do with the table deleting itself when going fullscreen. That logic is in the MRT_TableRoot component.

**Comment by duckboy81** [comment] 2023-01-11 01:46
It's interesting for sure. I'm chasing a lead in the following code. It seems if I set `bottomToolbarHeight` to something small (`0` or even `1`) it had no issues.

https://github.com/KevinVandy/material-react-table/blob/aa72893599d091fd0a77f7d1732219f36e13e33d/packages/material-react-table/src/table/MRT_TableContainer.tsx#L28-L40

The only consumer of `totalToolbarHeight` is the `TableContainer` component.

https://github.com/KevinVandy/material-react-table/blob/aa72893599d091fd0a77f7d1732219f36e13e33d/packages/material-react-table/src/table/MRT_TableContainer.tsx#L54-L69

We'll see what I come up with.

**Comment by KevinVandy** [comment] 2023-01-11 01:59
@duckboy81 Welp, you have found the ugliest code in the MRT codebase probably lol. I actually wish to delete it, but I think it was the only way to do... something... I think get rid of a scrollbar in fullscreen mode?

**Comment by KevinVandy** [comment] 2023-01-11 02:28
> @KevinVandy Alright, pull request submitted. If that comes through clean on your end, I wonder if we should also update `MRT_TopToolbar` and/or `MRT_TablePaper` to match.

Adding the `if` checks? probably

**Closed by KevinVandy** 2023-01-11 02:28 UTC
