### ISSUE TITLE
Filtered icon tooltip write "undefined" when you use custom filterFn

### ISSUE THREAD

**Issue by KarachunVladislav01** [KevinVandy/material-react-table#563] opened 2023-06-12 16:53 UTC
### material-react-table version

1.11.4

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

Thanks for good library!

Issue found:
When you use custom filterFn.

Steps to reproduce on attached example(from official storybook): 

1) Write something at gender filter
2) Move cursor to gender filter Icon

Mb possible solution can be - turn off filter tooltip, or customize tooltip body with filter props.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.dev/?path=/story/features-filtering-examples--custom-filter-fns

### Screenshots or Videos (Optional)

![Screenshot from 2023-06-12 20-37-17](https://github.com/KevinVandy/material-react-table/assets/16011734/106eb7cb-fe2a-4f70-baef-967d26cae0da)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2023-06-12 19:50
duplicate of #201 

The filtering docs shows you how to fix this https://www.material-react-table.com/docs/guides/column-filtering#customize-filter-modes-source-code

**Closed by KevinVandy** 2023-06-12 19:50 UTC

**Comment by RiaBatraTR** [comment] 2023-07-25 08:35
@KevinVandy Hi,

can we disable these tooltips? or change the text completely
