### ISSUE TITLE
Virtual Rows Blink When Rows Have Varying Heights On Scroll

### ISSUE THREAD

**Issue by scott-avery** [KevinVandy/material-react-table#37] opened 2022-08-09 08:01 UTC
### material-react-table version

0.33.6

### Describe the bug and the steps to reproduce it

1. Open https://www.material-react-table.dev/?path=/story/features-virtualization--enable-row-virtualization
2. perform some scrolls on table.
3. glitches occur.

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://www.material-react-table.dev/?path=/story/features-virtualization--enable-row-virtualization

### Screenshots or Videos (Optional)

![capture](https://user-images.githubusercontent.com/105617446/183596844-3fcf8c5c-f2d3-45c4-9472-fe3f400a1fac.gif)

![capture2](https://user-images.githubusercontent.com/105617446/183596735-f1daa946-356c-413d-9762-9f09ff8d5ed1.gif)

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2022-08-09 12:39
I'm exploring if I need to roll back to a previous beta version of `@tanstack/react-virtual` or even back to `react-virtual` v2 which did not have this problem

**Comment by KevinVandy** [comment] 2022-08-10 03:03
as of `v0.34.0`, it has been rolled back to react-virtual v2.10.4 where the problem does not appear to exist. Something is off with the estimateSize or scrolling ref logic in v3.

**Comment by scott-avery** [comment] 2022-08-10 07:46
@KevinVandy I am afraid that issue still exists after rollback. Scroll more and you will find some rows flickering.

Both from online storybook and my local clone storybook.

My browser version is Chrome 104.0.5112.81.

**Comment by KevinVandy** [comment] 2022-08-10 11:59
> @KevinVandy I am afraid that issue still exists after rollback. Scroll more and you will find some rows flickering.
> 
> Both from online storybook and my local clone storybook.
> 
> My browser version is Chrome 104.0.5112.81.

By flickering do you mean that it takes a second for the new rows to fully render in? Or are you still seeing large up and down vibrations that never stop.

There might always be some delay in the rows rendering. The uncontrolled infinite bouncing up and down is what I'm hoping is solved now.

**Comment by scott-avery** [comment] 2022-08-11 02:18
@KevinVandy it's about the vibrations. It might be some calculation edge case in that library.

**Comment by KevinVandy** [comment] 2022-08-14 14:15
@scott-avery I've tried to find the problem on v0.36.0 on a Mac, Windows PC, and Android phone, and don't see the vertical vibrations anymore on my storybook or docs site. I can re-open if it is confirmed to still be happening though.

More work in general is needed for virtualization performance. Really want to be able to use `@tanstack/react-virtual` v3 once this is figured out.

**Comment by e-cloud** [comment] 2022-08-16 15:56
I think I could reproduce it too. Easily with large row size.
![react-table](https://user-images.githubusercontent.com/5255354/184924578-da11815f-e31c-4a01-b374-9e7fbb322ab6.gif)

**Comment by KevinVandy** [comment] 2022-08-21 18:50
Tried for hours to improve this, but it seems to be a flaw with react-virtual where when rows are differing heights are scrolled into and out of view at the same time cause this jitter. Slight improvements have been made by using some measureRefs internally, but the main fix is to ensure all rows have the same height. Setting a `compact` density state is one way to do that, since it sets `whitespace: nowrap;` internally on table cells.

**Comment by scott-avery** [comment] 2022-08-22 07:54
good job. I will also investigate how to improve it later.

**Comment by AndreyGrek** [comment] 2022-09-24 14:18
Good afternoon!
Faced the same problem that lines "dance". But we also got lags when adding components, for example:
- added enableExpanding
- added export with checkboxes
As I understand it, there is a constant rerender when scrolling and, accordingly, the more components, the more lags. Video with profiler enabled:

https://user-images.githubusercontent.com/42175541/192102312-932c00fa-82e3-4d9d-82df-36a638832374.mov

We managed to partially fix the lags by reducing the overscan:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/42175541/192102704-ad31bb18-414f-4424-be42-dfd9015be5e5.png">

But as I understand it, as the components in the table increase, the lags will reappear. Memo in virtualized table does not help :(

**Comment by KevinVandy** [comment] 2022-09-24 16:13
> But as I understand it, as the components in the table increase, the lags will reappear. Memo in virtualized table does not help :(

That's kind of the nature of the beast. The more features you enable, and the more rows and columns you render at once, the lower the performance will be. I recommend using pagination in those instances.

It does appear that virtualization and row expansion don't play well together. Makes sense as any row height variation seems to confuse `react-virtual`

**Comment by AndreyGrek** [comment] 2022-09-24 17:51
It's so sad. But I'll still look for a solution, if I write something here or expose it to you PR

**Comment by KevinVandy** [comment] 2022-12-08 19:00
Good News. This will be fixed in v1.4. Thanks in part to @AndreyGrek 's PR.

**Comment by KevinVandy** [comment] 2022-12-09 00:28
@AndreyGrek @scott-avery @e-cloud For those of you still using this library, v1.4.0 now has addressed the major problems here. This should be fixed

**Closed by KevinVandy** 2022-12-09 00:28 UTC
