### ISSUE TITLE
Issues with extra width on sub headers when using grid-no-grow and compact density

### ISSUE THREAD

**Issue by alexander7161** [KevinVandy/material-react-table#937] opened 2024-01-12 13:32 UTC
### material-react-table version

2.6.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

![image](https://github.com/KevinVandy/material-react-table/assets/9217537/2c053e08-29e2-4f4b-8404-9323fd19590e)

Currently with `layoutMode-"grid-no-grow"` and a compact density, multiple column headers are not properly aligned. There is an extra 1rem of width added to each header cell on the first row only.

Is there any way to disable this extra width to make the columns aligned with their sub columns?

Follow up to https://github.com/KevinVandy/material-react-table/issues/925

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/material-react-table-example-7nnqd2

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2024-01-19 22:09
There was a bug before where header group columns were 16px too short before, so this was added to fix that. Still trying to find the cause where this should be applied conditionally

**Comment by Webjin** [comment] 2024-01-20 09:33
In 2.8.0 I'm still running into this issue.
Seems like the 1rem in this line is causing the problem for me:
`    width: calc(var(--header-1_mrt_row_pin_mrt_row_pin-size) * 1px + 1rem);`

**Comment by alexander7161** [comment] 2024-01-20 11:04
@KevinVandy I think I didn't mention this originally, the issue seems to be when using a `density` that is not the default. I'm using `density: compact` together with `grid-no-grow` and the width of the first header row cells is `1rem` too much compared to the other header row cells and body cells.

**Comment by Webjin** [comment] 2024-01-21 16:16
For me it doesn't seem to matter what I set `density` to

**Comment by KevinVandy** [comment] 2024-01-21 16:32
Yeah, I guess I'll be getting rid of that + 1rem. It fixed widths for some, but broke them for others.

To be clear though, if need to fix it now for yourself, just change it yourself in muiTableHeadCellProps.sx on that column group definition

**Comment by KevinVandy** [comment] 2024-01-24 09:26
this has hopefully been resolved in v2.9.0

**Closed as completed by KevinVandy** 2024-01-24 09:26 UTC

**Comment by Webjin** [comment] 2024-01-24 09:31
Yes, so far I can confirm it has been solved. Excellent work mate <3 thnx a lot!
