### ISSUE TITLE
Column Ordering (DnD) not working on mobile device 

### ISSUE THREAD

**Issue by ahmedfeki** [KevinVandy/material-react-table#1137] opened 2024-05-18 01:16 UTC
### material-react-table version

2.13.0

### react & react-dom versions

18.1.0

### Describe the bug and the steps to reproduce it

Column Ordering (DnD) is working properly on PC but on mobile i can't drag  & drop 
Even in the [documentation example](https://www.material-react-table.com/docs/guides/column-ordering-dnd) on mobile it reproduce the same problem
 

### Minimal, Reproducible Example - (Optional, but Recommended)

[documentation example](https://www.material-react-table.com/docs/guides/column-ordering-dnd)

### Screenshots or Videos (Optional)

.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2024-06-03 21:06
duplicate of #577

**Closed as completed by KevinVandy** 2024-06-03 21:06 UTC
