### ISSUE TITLE
Scroll bar bouncing

### ISSUE THREAD

**Issue by ziggy6792** [KevinVandy/material-react-table#124] opened 2022-09-26 16:03 UTC
### material-react-table version

1.1.1

### Describe the bug and the steps to reproduce it

I am not sure.

I have attached a sample. It seems there is some bug in scrolling the rows. See from my video, after scrolling a bit suddenly the scroll bar starts to bounce up and down.
It seems from the console log that this is caused by an infinite update loop.

I have tested on chrome and firefox on mac.

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

Code sandbox
https://codesandbox.io/p/github/ziggy6792/material-react-table-issue/draft/recursing-moser?file=%2FREADME.md

Github
https://github.com/ziggy6792/material-react-table-issue

### Screenshots or Videos (Optional)

Dropbox screen recording of issue
(goto end to see issue)
https://www.dropbox.com/s/lp7dl6io2qync6o/material-react-table-issue.mov?dl=0

### Do you intend to try to help solve this bug with your own PR?

No, because I don't have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2022-09-26 16:19
Thanks for reporting, but this looks to be a duplicate of #37 . It is caused by a bug in `react-virtual`. The solution is to either ensure all rows have the same height, or to disable row virtualization

**Comment by ziggy6792** [comment] 2022-09-26 16:32
Hi

Yes I thought it might be related.
Disabled virtualization for now.

Thanks

**Comment by ziggy6792** [comment] 2022-09-26 16:45
One issue I have now though.

When I set `enableRowVirtualization={false}` then the row headers no longer float at the top as I scroll.
Is there a way to make that happen when `enableRowVirtualization` is off

![Screenshot 2022-09-27 at 12 44 40 AM](https://user-images.githubusercontent.com/60313838/192334192-31298955-142e-4a79-a232-ac3240acfbc0.png)

**Comment by KevinVandy** [comment] 2022-09-26 18:33
> One issue I have now though.
> 
> When I set `enableRowVirtualization={false}` then the row headers no longer float at the top as I scroll. Is there a way to make that happen when `enableRowVirtualization` is off
> 
> ![Screenshot 2022-09-27 at 12 44 40 AM](https://user-images.githubusercontent.com/60313838/192334192-31298955-142e-4a79-a232-ac3240acfbc0.png)

That's what the `enableStickyHeader` prop is for. It just also gets enabled automatically during virtualization

**Closed** 2022-09-27 00:37 UTC
