### ISSUE TITLE
Filter variant text: empty input, searches one letter at a time

### ISSUE THREAD

**Issue by u-can-do-it** [KevinVandy/material-react-table#1324] opened 2024-12-09 13:11 UTC
### material-react-table version

v3.0.2

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Filter: input value invisible, searches one letter at a time.
Open the [advanced example](https://www.material-react-table.com/docs/examples/advanced) and try to filter by name, salary and job title

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/devbox/relaxed-mahavira-c636mh

### Screenshots or Videos (Optional)

[ae97ec62-14d9-4b6a-a3db-94994003890d.webm](https://github.com/user-attachments/assets/b600361e-4d71-416b-9a20-61b932a3595e)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by UPSxACE** [comment] 2024-12-11 21:04
That bug was introduced on version 3.0.2

**Comment by tifosiblack** [comment] 2024-12-13 13:02
Hello guys, 

I'll take this one. It's due to a regression introduced in https://github.com/KevinVandy/material-react-table/pull/1273

I'll provide a PR.

Regards

**Comment by KevinVandy** [comment] 2024-12-13 13:53
fixed in v3.0.3. Honestly, this was a very bad bug and really should not have trusted a small pr that came in last week.

**Closed as completed by KevinVandy** 2024-12-13 13:53 UTC

**Comment by tifosiblack** [comment] 2024-12-13 14:22
No problem, indeed it was easily spotable. Glad I helped a bit and thanks for your the library.
