### ISSUE TITLE
Dynamically generated columns don't show up in show/hide column filter.

### ISSUE THREAD

**Issue by Bhavesh2105** [KevinVandy/material-react-table#287] opened 2022-12-28 09:57 UTC
### material-react-table version

1.4.0

### react & react-dom versions

18.2

### Describe the bug and the steps to reproduce it

1.  Initialize column with an empty array.
2. update the column using api response or after the first render of table.
3. All the date will be visible according to the dynamic column but inside the show/hide column filter columns will not be visible.

### Minimal, Reproducible Example - (Optional, but Recommended)

The table_list is coming from api.

```
const {
    table_list,
    isTableLoading,
    refetchTable,
    isTableError,
    isTableFetching,
  } = useGetMaster({
    master_name,
  });
const columns = useMemo(() => {
    if (table_list[0]) {
      const items = table_list[0];   
      return Object.keys(items || {}).map((item) => ({
        accessorKey: item,
        header: item,
        enableEditing: !item.includes("id"),
      }));
    }
    return [];
  }, [table_list]);
 
  return <MaterialReactTable
        {...defaultProps}
        columns={columns}
        data={table_list}
/>

````
The only solution that I have found is that if i don't render the table until I have response then it works perfectly but I also want to show the loading state.
  
  

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2022-12-28 13:51
Duplicate of #217 

I probably need to document this somewhere, but if have dynamic columns like that you also just have to manage the `columnOrder` state manually.

**Comment by Bhavesh2105** [comment] 2022-12-29 03:55
Handling `columnOrder` state manually works. But the position of `rowActions` can't be controlled now. Any way around this ?

**Closed** 2022-12-29 15:20 UTC
