### ISSUE TITLE
enableColumnResizing Props is not work with enableRowVirtualization Props

### ISSUE THREAD

**Issue by josecao** [KevinVandy/material-react-table#11] opened 2022-07-01 04:34 UTC
### material-react-table version

^0.16.2

### Describe the bug and steps to reproduce

If i use both enableColumnResizing and enableRowVirtualization, it only work with enableRowVirtualization and not work with enableColumnResizing.

### Expected behavior

work with both

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2022-07-01 05:02
It does not appear to be an issue with `enableRowVirtualization`, but rather when density is set to `compact`. I'll take a look at this and see why the resize handle gets hidden with dense padding

https://www.material-react-table.dev/?path=/story/features-virtualization--enable-row-virtualization-with-column-resizing

**Comment by KevinVandy** [comment] 2022-07-01 05:14
The density and column resizing bug should be fixed as of v0.17.1

If there is a virtualization bug that I could not reproduce, please let me know with a reproducible example. Otherwise I will consider this fixed.

**Comment by josecao** [comment] 2022-07-01 11:22
I am sorry, this is my mistake. Now, it work very good !!

**Comment by KevinVandy** [comment] 2022-07-01 13:08
No problem. Thanks for pointing out out!

**Closed** 2022-07-01 14:51 UTC
