### ISSUE TITLE
Can't perform a React state update on a component that hasn't mounted yet

### ISSUE THREAD

**Issue by bylly1** [KevinVandy/material-react-table#200] opened 2022-11-14 14:50 UTC
### material-react-table version

1.3.8

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I'm using `material-react-table` with redux `RTK Query` for fetching some that from backend and when I refresh the page I receive this error in the console.log
``` error
Warning: Can't perform a React state update on a component that hasn't mounted yet. This indicates that you have a side-effect in your render function that asynchronously later calls tries to update the component. Move this work to useEffect instead.
    at MRT_TableRoot
```

I think that the error is because I use `Suspense` for loading pages but I don t know how to fix the error

### Minimal, Reproducible Example - (Optional, but Recommended)

I don t have yet

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2022-11-14 18:02
This is just a warning. Duplicate of this discussion. https://github.com/KevinVandy/material-react-table/discussions/120

I'd like to look into what's causing this warning, but it's also not really a big deal and can safely be ignored.

PRs are welcome though

**Comment by Jarred808** [comment] 2022-12-15 06:07
For me I see this error when I have the table in a react functional component that is lazy loaded.

**Comment by bylly1** [comment] 2023-01-14 18:38
I temporary fixed the issue like this:
``` js
import { useState, useEffect } from 'react';
import MaterialReactTable from 'material-react-table';

const SomeTableComponent = () => {
 const [isMounted, setIsMounted] = useState<boolean>(false);
 
 useEffect(() => {
  setIsMounted(true);
  return () => setIsMounted(false);
 },[]);

 return (
  <>
   {isMounted && (
     <MaterialReactTable 
        ....material props
     />
   )
  </>
}
```

**Comment by KevinVandy** [comment] 2023-01-15 04:35
> I temporary fixed the issue like this:
> ``` js
> import { useState, useEffect } from 'react';
> import MaterialReactTable from 'material-react-table';
> 
> const SomeTableComponent = () => {
>  const [isMounted, setIsMounted] = useState<boolean>(false);
>  
>  useEffect(() => {
>   setIsMounted(true);
>   return () => setIsMounted(false);
>  },[]);
> 
>  return (
>   <>
>    {isMounted && (
>      <MaterialReactTable 
>         ....material props
>      />
>    )
>   </>
> }
> ```

Interesting. Maybe I just need to add this to the Table Root internally

**Comment by KevinVandy** [comment] 2023-02-13 12:36
FYI, I don't think I will be adding this code internally to fix the issue. Doing so actually causes a delay in rendering, and some extra flickering. For those who really want the warning to go away though, the above works.

**Closed by KevinVandy** 2023-02-13 12:36 UTC
