### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'duration')

### ISSUE THREAD

**Issue by israelcarneiro** [KevinVandy/material-react-table#734] opened 2023-10-13 18:19 UTC
### material-react-table version

v1.15.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

While attempting to use Material-React-Table, I've observed that I am encountering an error that throws the message "TypeError: Cannot read properties of undefined (reading 'duration')." The error occurs during the execution of a code example provided by the library. I have already followed the installation instructions and verified that all necessary dependencies have been installed correctly.

Steps to Reproduce the Error:
Install the required dependencies: ` yarn add material-react-table @mui/material @mui/icons-material @emotion/react @emotion/styled`

Execute the example code provided by the library. For instance, you can use the following example code:
``` typescript

import React, { useMemo } from 'react';

import MaterialTable from 'material-react-table';

const data = [
	{ id: 1, name: 'Item 1', duration: 10 },
	{ id: 2, name: 'Item 2', duration: 20 }
	// ...
];

const columns = useMemo(
	() => [
		{
			accessorKey: 'id',
			enablePinning: false, //disable column pinning for this column
			header: 'ID',
			size: 50
		},
		{
			accessorKey: 'firstName',
			header: 'First Name'
		},
		{
			accessorKey: 'middleName',
			header: 'Middle Name'
		},
		{
			accessorKey: 'lastName',
			header: 'Last Name'
		},
		{
			accessorKey: 'address',
			header: 'Address',
			size: 300
		},
		{
			accessorKey: 'city', //this column gets pinned to the right by default because of the initial state,
			header: 'City'
		},

		{
			accessorKey: 'state', //this column gets pinned left by default because of the the initial state,
			header: 'State'
		}
	],
	[]
);

function App() {
	return (
		<div>
			<MaterialTable data={data} columns={columns} />
		</div>
	);
}

export default App;

```

### Minimal, Reproducible Example - (Optional, but Recommended)

I think it's not necessary

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/58194067/16b20f68-de07-40ea-b421-a7b7e23b20da)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2023-10-17 21:45
I'm guessing that those are not your actual column definitions? None of those columns are trying to access your `duration` data at all

**Comment by KevinVandy** [comment] 2024-01-09 18:59
closing as a vague issue probably caused by installing bad mismatching versions

**Closed as completed by KevinVandy** 2024-01-09 18:59 UTC

**Comment by Linux-Alex** [comment] 2024-12-27 00:17
I got the same problem:

![Screenshot_20241227_011644](https://github.com/user-attachments/assets/3e989a3a-3e0b-4e5f-9407-63cb4e537678)
